stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: mvn compile

job 2:
  stage: test
  script: mvn test

job 3:
  stage: deploy
  script:
     - mvn package
     - export PORT=5001
     - sh target/bin/simplewebapp
     - dpl -provider=heroku --app=qs4617-simplewebapp2 --api-key=dbac4f33-4a03-4e58-a345-9773299bc3aa

