stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: mvn compile

job 2:
  stage: test
  script: mvn test

job 3:
  stage: deploy
  script:
    - dpl --provider=heroku --app=qs4617-simplewebapp2 --api-key=431f39e2-0ec2-418e-bd69-c6d40dbde83a
#     - mvn package
#     - export PORT=5000
#     - sh target/bin/simplewebapp
