stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: mvn compile

job 2:
  stage: test
  script: mvn test

job 3:
  stage: deploy
  script:
      - mvn package
      - export PORT=5000
      - sh target/bin/simplewebapp
      - dpl -provider=heroku --app=qs4617-simplewebapp2 --api-key=1633c976-c88d-42ca-ba25-fb18da921681

